
name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # end of every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: llvm
          base: master
          head: master
          auto_approve: true
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
